### ISSUE TITLE
switching back to automatic 

### ISSUE THREAD

**Issue by Luftloch80** [lukasroegner/homebridge-tado#1]
Servus. Plugin läuft so weit mega stabil. 
Wenn ich für eine Urlaubschaltung alle Thermostate mit heizen auf 19 Grad stelle macht er das ohne Probleme. 
Wenn ich dann wieder mit einer Automation alle Thermostate auf Automatisch stelle passiert in der Tado App leider nix und die Thermostate bleiben auf manuell 
Er Switch nicht zurück auf automatisch

**Comment by lukasroegner** [comment]
Hi @Luftloch80,

Please start homebridge in Debug mode (add the parameter `-D` to the command to start homebridge). Then, execute the automation and provide the logs, so that we can checks for issues.

Best regards
Lukas

**Comment by Luftloch80** [comment]
This Happens when switching back to automatic Heating. 
Temperatures are taken but Not the automatic Mode

2020, 7:38:02 PM] [Diskstation] current power state is: true
[1/23/2020, 7:38:04 PM] [TadoPlatform] 15 - Switch target state to AUTO
[1/23/2020, 7:38:04 PM] [TadoPlatform] 11 - Switch target state to AUTO
[1/23/2020, 7:38:04 PM] [TadoPlatform] 1 - Set target temperature to 22.5
[1/23/2020, 7:38:04 PM] [TadoPlatform] 14 - Switch target state to AUTO
[1/23/2020, 7:38:04 PM] [TadoPlatform] 4 - Switch target state to AUTO
[1/23/2020, 7:38:04 PM] [TadoPlatform] 12 - Switch target state to AUTO
[1/23/2020, 7:38:04 PM] [TadoPlatform] 12 - Set target temperature to 18
[1/23/2020, 7:38:04 PM] [TadoPlatform] 15 - Set target temperature to 20
[1/23/2020, 7:38:04 PM] [TadoPlatform] 4 - Set target temperature to 22
[1/23/2020, 7:38:04 PM] [TadoPlatform] 11 - Set target temperature to 23
[1/23/2020, 7:38:04 PM] [TadoPlatform] 1 - Switch target state to AUTO
[1/23/2020, 7:38:04 PM] [TadoPlatform] 14 - Set target temperature to 22
(node:22134) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /usr/local/lib/node_modules/homebridge-tado/src/tado-heating-zone.js:150:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22134) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22134) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /usr/local/lib/node_modules/homebridge-tado/src/tado-heating-zone.js:150:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:22134) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /usr/local/lib/node_modules/homebridge-tado/src/tado-heating-zone.js:150:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:22134) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /usr/local/lib/node_modules/homebridge-tado/src/tado-heating-zone.js:150:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:22134) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /usr/local/lib/node_modules/homebridge-tado/src/tado-heating-zone.js:150:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:22134) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /usr/local/lib/node_modules/homebridge-tado/src/tado-heating-zone.js:150:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
[1/23/2020, 7:38:04 PM] [TadoPlatform] 14 - Updated state.
[1/23/2020, 7:38:04 PM] [TadoPlatform] 4 - Updated state.
[1/23/2020, 7:38:04 PM] [TadoPlatform] 11 - Updated state.
[1/23/2020, 7:38:04 PM] [TadoPlatform] 15 - Updated state.
[1/23/2020, 7:38:04 PM] [TadoPlatform] 1 - Updated state.
[1/23/2020, 7:38:04 PM] [TadoPlatform] 12 - Updated state.

**Comment by lukasroegner** [comment]
Thank you, that helped resolving a bug in the login mechanism (new version on master branch).
The updates does not resolve your issue with switching back to auto.

However, the logs show that the temperature is also set. Did you add that intentionally to your automation? Just switching back to auto would be enough, as the auto-temperature is automatically set by tado.

**Comment by Luftloch80** [comment]
When selecting thermostat ist always Sets a Temperature also when selecting automatisch 

![IMG_0803](https://user-images.githubusercontent.com/20800008/73020325-b0414100-3e25-11ea-8151-971c440cb0ac.png)

23/2020, 8:22:42 PM] [TadoPlatform] 11 - Switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 1 - Set target temperature to 22.5
[1/23/2020, 8:22:42 PM] [TadoPlatform] 14 - Switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 4 - Switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 12 - Switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 12 - Set target temperature to 18
[1/23/2020, 8:22:42 PM] [TadoPlatform] 15 - Set target temperature to 20
[1/23/2020, 8:22:42 PM] [TadoPlatform] 4 - Set target temperature to 22
[1/23/2020, 8:22:42 PM] [TadoPlatform] 11 - Set target temperature to 23
[1/23/2020, 8:22:42 PM] [TadoPlatform] 1 - Switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 14 - Set target temperature to 19
[1/23/2020, 8:22:42 PM] [TadoPlatform] 11 - Failed to switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 1 - Failed to switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 14 - Failed to switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 12 - Failed to switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 15 - Failed to switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 4 - Failed to switch target state to AUTO
[1/23/2020, 8:22:42 PM] [TadoPlatform] 14 - Updated state.
[1/23/2020, 8:22:42 PM] [TadoPlatform] 11 - Updated state.
[1/23/2020, 8:22:42 PM] [TadoPlatform] 15 - Updated state.
[1/23/2020, 8:22:42 PM] [TadoPlatform] 1 - Updated state.
[1/23/2020, 8:22:42 PM] [TadoPlatform] 4 - Updated state.
[1/23/2020, 8:22:42 PM] [TadoPlatform] 12 - Updated state.

**Comment by lukasroegner** [comment]
I see, please open the automation in a third-party HomeKit app like Controller for HomeKit or Eve. There, you should be able to remove setting the temperature.
